### ISSUE TITLE
请问是用的什么软件/插件转换的html或者渲染的markdown

### ISSUE THREAD

**Issue by caijimoyu** [aoaostar/legado#1]
![image](https://user-images.githubusercontent.com/102563512/216532650-ec91e583-437d-4b3b-b53f-4fa3f0c2f609.png)
网页查看时存在两个超链接格式渲染错误

**Comment by aoaostar** [comment]
markdown2这个包的最新版有点问题，所以转化异常了
已经指定了包可用版本
感谢反馈☺️
