### ISSUE TITLE
全量书源解析报错

### ISSUE THREAD

**Issue by xiexindev** [aoaostar/legado#7]
![Screenshot_2023-10-14-22-40-31-495_io legado app release](https://github.com/aoaostar/legado/assets/19523795/492b55cf-0e02-4a39-a622-bd63a93715b2)

**Comment by SunshineboyZj** [comment]
+1
![275288458-70834752-d702-4df4-bbcd-2671e0b2b0bc](https://github.com/aoaostar/legado/assets/81549837/937b98c1-2067-496d-b2c7-68cead572e93)

**Comment by aoaostar** [comment]
可以导全量书源 (服务端已校检) 🔥这个书源，这是校检过的
