### ISSUE TITLE
全量书源导入报错

### ISSUE THREAD

**Issue by SunshineboyZj** [aoaostar/legado#9]
![Screenshot_20231106_191223](https://github.com/aoaostar/legado/assets/81549837/a0292c82-008f-44f7-95ed-3928f13f3463)

**Comment by aoaostar** [comment]
可以导`全量书源 (服务端已校检) 🔥`这个书源，这是校检过的

**Comment by SunshineboyZj** [comment]
> 可以导`全量书源 (服务端已校检) 🔥`这个书源，这是校检过的

但上面那个一直导入不了也不是个事啊😂
如果能解决一下的话就好了💐

**Comment by aoaostar** [comment]
> > 可以导`全量书源 (服务端已校检) 🔥`这个书源，这是校检过的
> 
> 但上面那个一直导入不了也不是个事啊😂 如果能解决一下的话就好了💐

空了修，能提pull request就更好了🙂
